name: Sinsnag Talk Dev

on:
  pull_request:
    branches: 
      - "xx"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: '배포할 환경을 선택해주세요'
        required: true
        options:
        - dev
        - stage
        - qa
        - prod

jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: echo Hello, Dealicious

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: it-prod
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
